version: "3.8"

services:
    thesis_test_case:
        build: .
        container_name: thesis_test_case
        command: > 
            sh -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on:
            - thesis_db
    thesis_db:
        image: postgres
        container_name: thesis_db
        environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        expose:
          - '5432'
        ports:
          - '5105:5432'